import localFont from "next/font/local";
import Layout from "@/components/General/Layout/Layout";

import "swiper/swiper.min.css";
import "./globals.css";
import Providers from "./providers";
import { ClerkProvider } from "@clerk/nextjs/app-beta";

export const metadata = {
  title: "Nike Air Max",
  description: "Generated by create next app",
};

const monumentRegular = localFont({
  src: "../public/fonts/MonumentExtended-Regular.otf",
  variable: "--font-regular",
  display: "swap",
});

const monumentUltrabold = localFont({
  src: "../public/fonts/MonumentExtended-Ultrabold.otf",
  variable: "--font-ultrabold",
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${monumentRegular.variable} ${monumentUltrabold.variable}`}
    >``
      <ClerkProvider>
      <body>
        <Providers>
          <Layout>{children}</Layout>
        </Providers>
      </body>
      </ClerkProvider>
    </html>
  );
}
